import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import PropositionAnalyzer from './PropositionAnalyzer'
import ProofContainer from './ProofContainer'

const enter = (label, value) => fireEvent.change(screen.getByLabelText(label, { exact: true }), { target: { value } })
const click = (name) => fireEvent.click(screen.getByRole('button', { name, exact: true }))

test('analyzer distinguishes a leading negation from the main connective and clears invalid results', () => {
    render(<PropositionAnalyzer />)
    enter('Proposition', '~P ∨ Q')
    expect(screen.getByText(/Main Operator:/).parentElement).toHaveTextContent('Disjunction')
    expect(screen.getByText(/Classification:/).parentElement).toHaveTextContent('Contingency')
    expect(screen.getByRole('table')).toBeInTheDocument()

    enter('Proposition', '~(P ∨)')
    expect(screen.getByRole('alert')).toHaveTextContent('Not a well-formed formula')
    expect(screen.queryByText(/Main Operator:/)).not.toBeInTheDocument()
    expect(screen.queryByRole('table')).not.toBeInTheDocument()
})

test('analyzer shows tautologies and quantifier scope without inventing predicate truth tables', () => {
    render(<PropositionAnalyzer />)
    enter('Proposition', 'P -> P')
    expect(screen.getByText(/Classification:/).parentElement).toHaveTextContent('Tautology')
    enter('Proposition', '∀xP(x) ⊃ Q(x)')
    expect(screen.getByText(/Free variables:/).parentElement).toHaveTextContent('x')
    expect(screen.getByText(/Bound variables:/).parentElement).toHaveTextContent('x')
    expect(screen.getByText(/Open formula:/)).toBeInTheDocument()
    expect(screen.queryByRole('table')).not.toBeInTheDocument()
})

test('symbol insertion replaces selected text and restores the caret', async () => {
    render(<PropositionAnalyzer />)
    enter('Proposition', 'P & Q')
    const input = screen.getByLabelText('Proposition', { exact: true })
    input.focus()
    input.setSelectionRange(2, 3)
    click('Insert conjunction into proposition')
    await waitFor(() => expect(input).toHaveValue('P · Q'))
    await waitFor(() => expect(input.selectionStart).toBe(3))
    expect(input).toHaveFocus()
})

test('proof assistant checks modus ponens, completes a proof, and can undo', () => {
    render(<ProofContainer />)
    click('Load modus ponens example')
    click('Start proof')
    enter('Next formula', 'Q')
    enter('Cited lines', '1, 2')
    click('Check and add line')
    expect(screen.getByText(/Proof complete:/)).toBeInTheDocument()
    expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(4)
    click('Undo last line')
    expect(screen.queryByText(/Proof complete:/)).not.toBeInTheDocument()
    expect(screen.getByLabelText('Next formula', { exact: true })).toBeInTheDocument()
})

test('proof assistant rejects a mismatched conclusion and exposes a counterexample for an invalid argument', () => {
    render(<ProofContainer />)
    enter('Premises', 'P ⊃ Q\nQ')
    enter('Goal', 'P')
    click('Start proof')
    expect(screen.getByText('The goal does not follow from the premises.')).toBeInTheDocument()
    expect(screen.getByText(/Counterexample:/)).toHaveTextContent('P = F')
    enter('Next formula', 'P')
    enter('Cited lines', '1, 2')
    click('Check and add line')
    expect(screen.getByRole('alert')).toBeInTheDocument()
    expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(3)
    expect(screen.queryByText(/Proof complete:/)).not.toBeInTheDocument()
})

test('proof assistant supports a premise-free theorem through a discharged assumption', () => {
    render(<ProofContainer />)
    enter('Goal', 'P ⊃ P')
    click('Start proof')
    enter('Next formula', 'P')
    enter('Rule', 'assume')
    click('Check and add line')
    expect(screen.getByText(/Working inside 1 open subproof/)).toBeInTheDocument()
    enter('Next formula', 'P ⊃ P')
    enter('Rule', 'cp')
    enter('Cited lines', '1, 1')
    click('Check and add line')
    expect(screen.getByText(/Proof complete:/)).toBeInTheDocument()
})

test('proof hints populate an explicit step for the user to check', () => {
    render(<ProofContainer />)
    click('Load modus ponens example')
    click('Start proof')
    click('Show hints')
    click('Use Q')
    expect(screen.getByLabelText('Next formula', { exact: true })).toHaveValue('Q')
    expect(screen.getByLabelText('Cited lines', { exact: true })).toHaveValue('1, 2')
    click('Check and add line')
    expect(screen.getByText(/Proof complete:/)).toBeInTheDocument()
})

test('predicate example can be proved through universal instantiation and modus ponens', () => {
    render(<ProofContainer />)
    click('Load predicate example')
    click('Start proof')
    enter('Next formula', 'P(a) ⊃ Q(a)')
    enter('Rule', 'ui')
    enter('Cited lines', '1')
    enter('Substitution term', 'a')
    click('Check and add line')
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    enter('Next formula', 'Q(a)')
    enter('Rule', 'mp')
    enter('Cited lines', '3, 2')
    click('Check and add line')
    expect(screen.getByText(/Proof complete:/)).toBeInTheDocument()
})
